package com.example.baseproject3_foodrecipe.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

// Light Theme Colors
val md_theme_light_primary = Color(0xFFD32F2F)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFCDD2)
val md_theme_light_onPrimaryContainer = Color(0xFF410002)
val md_theme_light_secondary = Color(0xFFFFAB40)
val md_theme_light_onSecondary = Color(0xFF212121)
val md_theme_light_secondaryContainer = Color(0xFFFFDDB8)
val md_theme_light_onSecondaryContainer = Color(0xFF2A1800)
val md_theme_light_tertiary = Color(0xFF8BC34A)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC5E1A5)
val md_theme_light_onTertiaryContainer = Color(0xFF102000)
val md_theme_light_error = Color(0xFFF44336)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFF9F5)
val md_theme_light_onBackground = Color(0xFF212121)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF212121)
val md_theme_light_surfaceVariant = Color(0xFFF5F5F5)
val md_theme_light_onSurfaceVariant = Color(0xFF757575)
val md_theme_light_outline = Color(0xFFE0E0E0)
val md_theme_light_inverseOnSurface = Color(0xFFF5F5F5)
val md_theme_light_inverseSurface = Color(0xFF424242)
val md_theme_light_inversePrimary = Color(0xFFFFB3B3)
val md_theme_light_surfaceTint = Color(0xFFD32F2F)
val md_theme_light_outlineVariant = Color(0xFFEEEEEE)
val md_theme_light_scrim = Color(0xFF000000)

// Dark Theme Colors
val md_theme_dark_primary = Color(0xFFFF5252)
val md_theme_dark_onPrimary = Color(0xFF212121)
val md_theme_dark_primaryContainer = Color(0xFF9A0000)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDAD4)
val md_theme_dark_secondary = Color(0xFFFFC107)
val md_theme_dark_onSecondary = Color(0xFF212121)
val md_theme_dark_secondaryContainer = Color(0xFF624000)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDDB8)
val md_theme_dark_tertiary = Color(0xFF689F38)
val md_theme_dark_onTertiary = Color(0xFFFFFFFF)
val md_theme_dark_tertiaryContainer = Color(0xFF4B830D)
val md_theme_dark_onTertiaryContainer = Color(0xFFC5E1A5)
val md_theme_dark_error = Color(0xFFE53935)
val md_theme_dark_errorContainer = Color(0xFF9C0000)
val md_theme_dark_onError = Color(0xFFFFFFFF)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF212121)
val md_theme_dark_onBackground = Color(0xFFFFFFFF)
val md_theme_dark_surface = Color(0xFF424242)
val md_theme_dark_onSurface = Color(0xFFFFFFFF)
val md_theme_dark_surfaceVariant = Color(0xFF616161)
val md_theme_dark_onSurfaceVariant = Color(0xFFBDBDBD)
val md_theme_dark_outline = Color(0xFF757575)
val md_theme_dark_inverseOnSurface = Color(0xFF212121)
val md_theme_dark_inverseSurface = Color(0xFFF5F5F5)
val md_theme_dark_inversePrimary = Color(0xFFD32F2F)
val md_theme_dark_surfaceTint = Color(0xFFFF5252)
val md_theme_dark_outlineVariant = Color(0xFF424242)
val md_theme_dark_scrim = Color(0xFF000000)

// Food Category Colors (consistent in both themes)
val md_food_sushi = Color(0xFFFF7043)
val md_food_veggie = Color(0xFF8BC34A)
val md_food_meat = Color(0xFFE53935)
val md_food_seafood = Color(0xFF2196F3)
val md_food_dessert = Color(0xFF9C27B0)

// Semantic Colors
val md_semantic_success = Color(0xFF4CAF50)
val md_semantic_warning = Color(0xFFFFC107)
val md_semantic_error = Color(0xFFF44336)
val md_semantic_info = Color(0xFF2196F3)

// Extended Colors
val md_extended_rating = Color(0xFFFFC107)
val md_extended_time = Color(0xFF4CAF50)
val md_extended_difficulty_easy = Color(0xFF4CAF50)
val md_extended_difficulty_medium = Color(0xFFFFC107)
val md_extended_difficulty_hard = Color(0xFFF44336)